SET ANSI_NULLS ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET ARITHABORT ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET QUOTED_IDENTIFIER ON;
SET NUMERIC_ROUNDABORT OFF;
GO
UPDATE [dbo].[Users] SET [PasswordHash] = '$2a$12$MoqhJ5opV8GUS1nhtID/vuRtCTP50HOj.OaSkWj2IIsrzi1sNM3cG' WHERE [UserName] = 'binhnguyen';
GO